#tarslog
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarslog','192.168.2.131','tars.tarslog.LogObjAdapter',now(),5,'tcp -h 192.168.2.131 -t 60000 -p 10003',200000,'','tars.tarslog.LogObj',10000,60000,now(),NULL,'tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`) VALUES ('tars','tarslog','','192.168.2.131',now(),'','/usr/local/app/tars/tarslog/bin/tarslog','tars.tarslog',0,'active','inactive',0,'1',now(),'','1.0.1',now(),'admin','tars_cpp');

#tarspatch
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarspatch','192.168.2.131','tars.tarspatch.PatchObjAdapter',now(),10,'tcp -h 192.168.2.131 -t 60000 -p 10000',200000,'','tars.tarspatch.PatchObj',10000,60000,now(),'admin','tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`) VALUES ('tars','tarspatch','','192.168.2.131',now(),'','/usr/local/app/tars/tarspatch/bin/tarspatch','tars.tarspatch',0,'active','inactive',3807,'',now(),'','1.0.1',now(),'admin','tars_cpp');

#tarsqueryproperty
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarsqueryproperty','192.168.2.131','tars.tarsqueryproperty.NoTarsObjAdapter',now(),5,'tcp -h 192.168.2.131 -t 60000 -p 10011',200000,'','tars.tarsqueryproperty.NoTarsObj',10000,60000,now(),NULL,'not_tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`, `profile`) VALUES ('tars','tarsqueryproperty','','192.168.2.131',now(),'','/usr/local/app/tars/tarsqueryproperty/bin/tarsqueryproperty','tars.tarsproperty',0,'active','inactive',6405,'57',now(),'','1.0.1',now(),NULL,'tars_cpp','<tars>\n<countdb>\n<db1>\n  dbhost=192.168.2.131\n                      dbname=tars_property\n                  tbname=tars_property_\n                 dbuser=tars\n                   dbpass=tars2015\n                   dbport=3306\n                   charset=utf8\n          </db1>\n</countdb>\n</tars>');

#tarsconfig
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarsconfig','192.168.2.131','tars.tarsconfig.ConfigObjAdapter',now(),10,'tcp -h 192.168.2.131 -t 60000 -p 10001',200000,'','tars.tarsconfig.ConfigObj',10000,60000,now(),'admin','tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`) VALUES ('tars','tarsconfig','','192.168.2.131',now(),'','/usr/local/app/tars/tarsconfig/bin/tarsconfig','tars.tarsconfig',0,'active','inactive',28007,'',now(),'','1.0.1','2015-08-08 10:49:37','admin','tars_cpp');

#tarsnotify

replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarsnotify','192.168.2.131','tars.tarsnotify.NotifyObjAdapter',now(),5,'tcp -h 192.168.2.131 -t 60000 -p 10002',200000,'','tars.tarsnotify.NotifyObj',10000,60000,now(),'admin','tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`) VALUES ('tars','tarsnotify','','192.168.2.131',now(),'','/usr/local/app/tars/tarsnotify/bin/tarsnotify','tars.tarsnotify',0,'active','inactive',9841,'52',now(),'','1.0.1',now(),'admin','tars_cpp');

#tarsproperty
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarsproperty','192.168.2.131','tars.tarsproperty.PropertyObjAdapter',now(),5,'tcp -h 192.168.2.131 -t 60000 -p 10005',200000,'','tars.tarsproperty.PropertyObj',10000,60000,now(),NULL,'tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`) VALUES ('tars','tarsproperty','','192.168.2.131',now(),'','/usr/local/app/tars/tarsproperty/bin/tarsproperty','tars.tarsproperty',0,'active','inactive',9393,'55',now(),'','1.0.1',now(),NULL,'tars_cpp');

#tarsquerystat
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarsquerystat','192.168.2.131','tars.tarsquerystat.NoTarsObjAdapter',now(),5,'tcp -h 192.168.2.131 -t 60000 -p 10012',200000,'','tars.tarsquerystat.NoTarsObj',10000,60000,now(),NULL,'not_tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`, `profile`) VALUES ('tars','tarsquerystat','','192.168.2.131',now(),'','/usr/local/app/tars/tarsquerystat/bin/tarsquerystat','tars.default',0,'active','inactive',6900,'59',now(),'','1.0.1',now(),NULL,'tars_cpp','<tars>\n<countdb>\n<db1>\n                   dbhost=192.168.2.131\n                      dbname=tars_stat\n                      tbname=tars_stat_\n                     dbuser=tars\n                   dbpass=tars2015\n                   dbport=3306\n                   charset=utf8\n          </db1>\n</countdb>\n</tars>');

#tarsstat
replace into `t_adapter_conf` (`application`, `server_name`, `node_name`, `adapter_name`,`registry_timestamp`, `thread_num`, `endpoint`, `max_connections`, `allow_ip`, `servant`, `queuecap`, `queuetimeout`,`posttime`,`lastuser`,`protocol`, `handlegroup`) VALUES ('tars','tarsstat','192.168.2.131','tars.tarsstat.StatObjAdapter',now(),5,'tcp -h 192.168.2.131 -t 60000 -p 10004',200000,'','tars.tarsstat.StatObj',10000,60000,now(),NULL,'tars','');

replace into `t_server_conf` (`application`, `server_name`, `node_group`, `node_name`, `registry_timestamp`, `base_path`, `exe_path`, `template_name`, `bak_flag`, `setting_state`, `present_state`, `process_id`, `patch_version`, `patch_time`, `patch_user`, `tars_version`, `posttime`, `lastuser`, `server_type`) VALUES ('tars','tarsstat','','192.168.2.131',now(),'','/usr/local/app/tars/tarsstat/bin/tarsstat','tars.tarsstat',0,'active','inactive',6487,'101',now(),'','1.1.0',now(),NULL,'tars_cpp');

